name: "action-doctum"
author: williamdes
description: "Use Doctum without having to install it"
inputs:
    config-file:
        description: "The configuration file"
        required: true
    method:
        description: "parse, render or update"
        required: true
    cli-args:
        description: "Command line arguments"
        default: '--output-format=github --no-ansi --no-progress -v'
        required: false
    user-id:
        description: "The user to execute the build, will be auto detected"
        default: ''
        required: false
    group-id:
        description: "The user to execute the build, will be auto detected"
        default: ''
        required: false

branding:
    icon: "book"
    color: blue
runs:
    using: "docker"
    image: "docker://botsudo/action-doctum:dev"
    env:
        USER_ID: "${{ inputs.user-id }}"
        GROUP_ID: "${{ inputs.group-id }}"
    args:
        - dev
        - "${{ inputs.config-file }}"
        - "${{ inputs.method }}"
        - "${{ inputs.cli-args }}"
