version: "3.3"

services:
    sut:
        build: .
        args:
            RELEASE_VERSION: '5'
        command: "5 ./doctum.php update"
        volumes:
          - ./tests:/tests:ro
        working_dir: /tests
