version: "3.3"

services:
    sut:
        build: .
        args:
            RELEASE_VERSION: 'dev'
        command: "dev ./doctum.php update"
        volumes:
          - ./tests:/tests:ro
        working_dir: /tests
