name: build doctum docs

permissions:
    contents: read

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: build doctum docs
              uses: sudo-bot/action-doctum@dev
              with:
                  config-file: docker/tests/doctum.php
                  method: "update"
                  cli-args: "--output-format=github --no-ansi --no-progress -v"
