name: build doctum docs
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: build doctum docs
              uses: sudo-bot/action-doctum@v5
              with:
                  config-file: tests/doctum.php
                  method: "update"
                  cli-args: "--output-format=github --no-ansi --no-progress"
